apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cron
spec:
  dependencies:
  - eventName: example-with-interval
    eventSourceName: calendar
    name: calendar-dep
  eventBusName: codefresh-eventbus
  template:
    container:
      name: ""
      resources: {}
    serviceAccountName: argo-server
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: eventTime
            dependencyName: calendar-dep
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: cron-
            spec:
              arguments:
                parameters:
                - name: message
              workflowTemplateRef:
                name: hello-world
      name: hello-world
