apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: flask
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
      eventName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
      eventSourceName: flask
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: build
        conditions: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: flask-build-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: exercise-temp-one-
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: nightmar39/flask-test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: csdp
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: dockerhub-registry-secret
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-dfee4dcb-209c-423b-94d8-3f82eecd822d
                dataTemplate: dockerhub-config-secret
