apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   labels:
    app.kubernetes.io/instance: codefresh-workflow-reporter
  name: my-wf-sa
  namespace: codefresh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codefresh-sa
subjects:
- kind: ServiceAccount
  name: my-wf-sa
  namespace: codefresh
