apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: proj
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-0d4f0484-e2f5-461a-b267-77463171a9ed:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - cf-test
      webhook:
        port: '80'
        method: POST
        endpoint: /webhooks/proj/github-0d4f0484-e2f5-461a-b267-77463171a9ed
        url: https://charizard.support.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
