apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: proj
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-3e485548-d775-4647-af61-e15068477ee0
      eventName: github-3e485548-d775-4647-af61-e15068477ee0
      eventSourceName: proj
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: build
        conditions: github-3e485548-d775-4647-af61-e15068477ee0
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: proj-build-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: nightmar39/test
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: cdsp
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: dockerfile
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: dockerhub-registry-secret
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-3e485548-d775-4647-af61-e15068477ee0
                dataTemplate: docker-config-secret
